### PR TITLE
Support vector-0.13

### LINKED ISSUE #82: Compatibility with vector-0.13
This will apparently require code changes:

```

src/System/IO/Streams/Vector.hs:80:46: error:
    • Couldn't match type ‘GHC.ST.ST VM.RealWorld’ with ‘IO’
      Expected type: V.Mutable v VM.RealWorld a -> IO (v a)
        Actual type: V.Mutable v VM.RealWorld a
                     -> GHC.ST.ST VM.RealWorld (v a)
    • In the second argument of ‘(>=>)’, namely ‘basicUnsafeFreeze’
      In the expression: toMutableVectorSized n >=> basicUnsafeFreeze
      In an equation for ‘toVectorSized’:
          toVectorSized n = toMutableVectorSized n >=> basicUnsafeFreeze
   |
80 | toVectorSized n = toMutableVectorSized n >=> V.basicUnsafeFreeze
   |                                              ^^^^^^^^^^^^^^^^^^^

src/System/IO/Streams/Vector.hs:139:5: error:
    • Couldn't match type ‘GHC.ST.ST s0 (v0 a0)’ with ‘IO (v c)’
      Expected type: IO (OutputStream c, IO (v c))
        Actual type: IO (OutputStream c, GHC.ST.ST s0 (v0 a0))
    • In a stmt of a 'do' block:
        return $! (os, flush >>= basicUnsafeFreeze)
      In the expression:
        do (os, flush) <- mutableVectorOutputStreamSized n
           return $! (os, flush >>= basicUnsafeFreeze)
      In an equation for ‘vectorOutputStreamSized’:
          vectorOutputStreamSized n
            = do (os, flush) <- mutableVectorOutputStreamSized n
                 return $! (os, flush >>= basicUnsafeFreeze)
    • Relevant bindings include
        flush :: GHC.ST.ST s0 (V.Mutable v0 s0 a0)
          (bound at src/System/IO/Streams/Vector.hs:138:10)
        os :: OutputStream c
          (bound at src/System/IO/Streams/Vector.hs:138:6)
        vectorOutputStreamSized :: Int -> IO (OutputStream c, IO (v c))
          (bound at src/System/IO/Streams/Vector.hs:137:1)
    |
139 |     return $! (os, flush >>= V.basicUnsafeFreeze)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/System/IO/Streams/Vector.hs:294:58: error:
    • Couldn't match type ‘GHC.ST.ST VM.RealWorld’ with ‘IO’
      Expected type: V.Mutable v VM.RealWorld a -> IO (v a)
        Actual type: V.Mutable v VM.RealWorld a
                     -> GHC.ST.ST VM.RealWorld (v a)
    • In the second argument of ‘(>=>)’, namely ‘basicUnsafeFreeze’
      In the expression:
        outputToMutableVectorSized n >=> basicUnsafeFreeze
      In an equation for ‘outputToVectorSized’:
          outputToVectorSized n
            = outputToMutableVectorSized n >=> basicUnsafeFreeze
    |
294 | outputToVectorSized n = outputToMutableVectorSized n >=> V.basicUnsafeFreeze
    |                                                          ^^^^^^^^^^^^^^^^^^^
cabal: Failed to build io-streams-1.5.2.1
```

Context: https://github.com/commercialhaskell/stackage/issues/6624

### PR DESCRIPTION
**Pull request by TeofilC**
This adds support for version 0.13 of the vector library by adding a compat shim around basicUnsafeFreeze

Fixes #82

### CODE REVIEW

**Review by andreasabel — APPROVED** [review]

**Review by mightybyte — APPROVED** [review]

**Comment by andreasabel** [comment]
@TeofilC : CI reports build failures with GHC 7, e.g.
```
[12 of 23] Compiling System.IO.Streams.Vector ( src/System/IO/Streams/Vector.hs, /__w/io-streams/io-streams/dist-newstyle/build/x86_64-linux/ghc-7.10.3/io-streams-1.5.2.1/build/System/IO/Streams/Vector.o )

src/System/IO/Streams/Vector.hs:46:54:
    Not in scope: type constructor or class ‘VM.RealWorld’
```
https://github.com/snapframework/io-streams/runs/7846023693?check_suite_focus=true#step:18:40

**Review by andreasabel — CHANGES_REQUESTED** [review]
`VM.RealWorld` not in scope with GHC < 8.

**Comment by TeofilC** [comment]
Good spot. I've forced a rebase and a change that imports it from Control.Monad.Primitive instead

**Comment by mightybyte** [comment]
New version released

**Comment by TeofilC** [comment]
Thanks!

**Pull request merged**
